DROP TABLE IF EXISTS copy;

CREATE TABLE copy(
    copyID INTEGER PRIMARY KEY  AUTOINCREMENT,
    bookISBN VARCHAR(20)NOT NULL,
    Available INT DEFAULT 1,
    FOREIGN KEY (bookISBN) REFERENCES Books(ISBN)
);
