-- Sample data for Genre table
-- GenreID is auto-increment, so we only need to specify the Genre name

INSERT INTO Genre (Genre) VALUES 
('Fiction'),
('Non-Fiction'),
('Science Fiction'),
('Fantasy'),
('Mystery'),
('Thriller'),
('Romance'),
('Horror'),
('Biography'),
('History'),
('Philosophy'),
('Science'),
('Technology'),
('Self-Help'),
('Business'),
('Health & Fitness'),
('Travel'),
('Cooking'),
('Art & Design'),
('Poetry'),
('Drama'),
('Adventure'),
('Crime'),
('Young Adult'),
('Children''s Literature'),
('Classic Literature'),
('Contemporary Fiction'),
('Historical Fiction'),
('Memoir'),
('Politics');