name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Biome lint
      run: npm run lint

    - name: Run Biome format check
      run: npm run check

    - name: Build CSS and TypeScript
      run: npm run build

    - name: Verify build outputs
      run: |
        echo "Checking build outputs..."
        ls -la dist/
        ls -la public/output.css
        echo "Build verification complete!"